apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: eks
        namespace: kube-system
      interval: 12h
  values:
    serviceAccount:
      create: true
      name: aws-load-balancer-controller
