apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tekton
  namespace: tekton-system
spec:
  interval: 30m
  chart:
    spec:
      chart: tekton-pipeline
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: cdf
        namespace: tekton-system
      interval: 12h
