apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: kube-system
      interval: 12h
  values:
    provider: aws
    sources:
      - service
      - ingress
    serviceAccount:
      create: false
      name: external-dns
